# Generated by Django 5.2.2 on 2025-06-25 22:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0002_alter_cursos_id_alter_cursos_categoria_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cursos',
            options={'ordering': ['created'], 'verbose_name': 'Curso', 'verbose_name_plural': 'Cursos'},
        ),
    ]
