# Generated by Django 5.2.2 on 2025-06-30 19:38

import ckeditor.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0004_alter_cursos_created_alter_cursos_updated'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cursos',
            old_name='ID',
            new_name='id',
        ),
        migrations.CreateModel(
            name='Actividad',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='Clave de la Actividad')),
                ('descripcionActividad', ckeditor.fields.RichTextField(verbose_name='Descripción de la Actividad')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Creado')),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cursos.cursos', verbose_name='Curso')),
            ],
            options={
                'verbose_name': 'Actividad',
                'verbose_name_plural': 'Actividades',
                'ordering': ['-created'],
            },
        ),
    ]
