# Generated by Django 5.2.2 on 2025-07-17 01:11

import ckeditor.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cursos',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='Id de Curso')),
                ('titulo', models.TextField(verbose_name='Título del Curso')),
                ('categoria', models.CharField(max_length=20, verbose_name='Categoría del Curso')),
                ('descripcion', models.TextField(verbose_name='Descripción del Curso')),
                ('profesor', models.TextField(verbose_name='Profesor que lo imparte')),
                ('imagen', models.ImageField(null=True, upload_to='foto', verbose_name='Fotografía')),
                ('created', models.DateField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de actualización')),
            ],
            options={
                'verbose_name': 'Curso',
                'verbose_name_plural': 'Cursos',
                'ordering': ['created'],
            },
        ),
        migrations.CreateModel(
            name='Actividad',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='Clave de la Actividad')),
                ('descripcionActividad', ckeditor.fields.RichTextField(verbose_name='Descripción de la Actividad')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Creado')),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenido.cursos', verbose_name='Curso')),
            ],
            options={
                'verbose_name': 'Actividad',
                'verbose_name_plural': 'Actividades',
                'ordering': ['-created'],
            },
        ),
    ]
