# Generated by Django 5.2.2 on 2025-06-25 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cursos',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False)),
                ('titulo', models.TextField()),
                ('categoria', models.CharField(max_length=20)),
                ('descripcion', models.TextField()),
                ('profesor', models.TextField()),
                ('imagen', models.ImageField(null=True, upload_to='foto', verbose_name='Fotografía')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
