# Generated by Django 5.2.2 on 2025-06-25 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cursos',
            name='ID',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='Id de Curso'),
        ),
        migrations.AlterField(
            model_name='cursos',
            name='categoria',
            field=models.CharField(max_length=20, verbose_name='Categoría del Curso'),
        ),
        migrations.AlterField(
            model_name='cursos',
            name='created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación'),
        ),
        migrations.AlterField(
            model_name='cursos',
            name='descripcion',
            field=models.TextField(verbose_name='Descripción del Curso'),
        ),
        migrations.AlterField(
            model_name='cursos',
            name='profesor',
            field=models.TextField(verbose_name='Profesor que lo imparte'),
        ),
        migrations.AlterField(
            model_name='cursos',
            name='titulo',
            field=models.TextField(verbose_name='Título del Curso'),
        ),
        migrations.AlterField(
            model_name='cursos',
            name='updated',
            field=models.DateField(auto_now_add=True, verbose_name='Fecha de actualización'),
        ),
    ]
