# Generated by Django 5.2.2 on 2025-06-25 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0003_alter_cursos_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cursos',
            name='created',
            field=models.DateField(auto_now_add=True, verbose_name='Fecha de creación'),
        ),
        migrations.AlterField(
            model_name='cursos',
            name='updated',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Fecha de actualización'),
        ),
    ]
